
# uuid
    import "github.com/eduncan911/go/pkg/uuid"

Package uuid exposes common methods for handling UUIDs in Go.

Based largely off of @abdullin's "id.go", this is a sharable version with a few
tweaks for Lint conditions to pass.







## type ID
``` go
type ID [16]byte
```
ID is a 16 byte array that represents the UUID





``` go
var (
    // EmptyID is a placeholder for an empty ID
    EmptyID ID
)
```




### func NewID
``` go
func NewID() ID
```
NewID returns a new UUID


### func ParseID
``` go
func ParseID(value string) (id ID, err error)
```
ParseID parses the specified string version of ID and returns an ID or an Error




### func (ID) Bytes
``` go
func (id ID) Bytes() []byte
```
Bytes return a bytes array



### func (ID) Equals
``` go
func (id ID) Equals(other ID) bool
```
Equals compares the specified ID to the underlying ID



### func (ID) IsEmpty
``` go
func (id ID) IsEmpty() bool
```
IsEmpty returns a boolean indicating the ID is empty



### func (ID) MarshalJSON
``` go
func (id ID) MarshalJSON() ([]byte, error)
```
MarshalJSON handles marshaling of this type



### func (ID) String
``` go
func (id ID) String() string
```
String returns a string-readable representation of the ID



### func (ID) Time
``` go
func (id ID) Time() time.Time
```
Time returns the time at which the ID was created



### func (\*ID) UnmarshalJSON
``` go
func (id *ID) UnmarshalJSON(data []byte) error
```
UnmarshalJSON handles unmarshaling this type









- - -
Generated by [godoc2md](http://godoc.org/github.com/davecheney/godoc2md)